Correcting typo and adjusting layering documentation
staircase-dev/staircase pull request #111
Opened 2021-10-01 21:51 UTC by strawhatasif

- [x] closes #https://github.com/staircase-dev/staircase/issues/101

2021-10-02 02:17 UTC, venaturum requested changes
Thanks @strawhatasif,

One of the typos is the missing quote marks which means the link to intro_tutorials.creating doesn't work.  Can you add them (ie :ref:`intro_tutorials.creating`)?

With regards to the changes to the mutator method sentence, a mutator method is one that modifies the state of its object and I feel that it is unclear with your proposed change.  Perhaps something like:

"it is the only mutator method, i.e. it is the only method which modifies the step function in place"

Cheers.

2021-10-02 19:43 UTC, strawhatasif commented
requested changes made to `layering.rst`

2021-10-03 03:03 UTC, venaturum approved these changes

2021-10-03 03:03 UTC, merged

2021-10-03 03:04 UTC, venaturum commented
Thanks @strawhatasif